#[derive(Debug, PartialEq, Clone)]
pub enum Token {
    Ident(String),
    Int(i64),
    Float(f64),
    String(String),
    LParen,
    RParen,
    Illegal(usize, String),
    EOF,
    Comma,
    NotEqual,
    Equal,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,
    Semicolon,
    Plus,
    Minus,
    Divide,
    Mod,
    True,
    False,
    Select,
    Insert,
    Delete,
    Update,
    Where,
    From,
    Into,
    Set,
    Star, // This is used for both select statements and multiplication - needs to be handled correctly in parser
    And,
    Or
}